# databases:
#   - name: personalblog
#     databaseName: personalblog
#     user: nitish
#     plan: free

# services:
#   - type: web
#     name: personalblog
#     runtime: ruby
#     plan: free
#     buildCommand: "./bin/render-build.sh"
#     # preDeployCommand: "bundle exec rails db:migrate" # preDeployCommand only available on paid instance types
#     startCommand: "bundle exec rails server"
#     envVars:
#       - key: DATABASE_URL
#         fromDatabase:
#           name: personalblog
#           property: connectionString
#       - key: RAILS_MASTER_KEY
#         sync: false
#       - key: WEB_CONCURRENCY
#         value: 2 # sensible default

# Exported from Render on 2024-07-10T10:28:22Z
services:
- type: web
  name: personalblog
  runtime: ruby
  repo: https://github.com/singhnitish12/personal-blog
  plan: free
  envVars:
  - key: RAILS_MASTER_KEY
    sync: false
  - key: WEB_CONCURRENCY
    sync: false
  - key: DATABASE_URL
    sync: false
  region: oregon
  buildCommand: ./bin/render-build.sh
  startCommand: bundle exec rails server
version: "1"
